// Runtime constants shared by main, preload and renderer. No Electron imports allowed here.
// The payload contract for each channel lives in src/@types/ipc.ts.
export const IPC_CHANNELS = {
  tabs: {
    getState: 'tabs:get-state',
    create: 'tabs:create',
    close: 'tabs:close',
    activate: 'tabs:activate',
    setChromeHeight: 'tabs:set-chrome-height',
    openHttpStatus: 'tabs:open-http-status',
    stateChanged: 'tabs:state-changed',
  },
  navigation: {
    navigate: 'navigation:navigate',
    goBack: 'navigation:go-back',
    goForward: 'navigation:go-forward',
    reload: 'navigation:reload',
    stop: 'navigation:stop',
  },
  ui: {
    focusAddressBar: 'ui:focus-address-bar',
    setTitleBarLayout: 'ui:set-title-bar-layout',
    windowControls: 'ui:window-controls',
  },
  menu: {
    toggle: 'menu:toggle',
    close: 'menu:close',
    select: 'menu:select',
    stateChanged: 'menu:state-changed',
  },
  account: {
    get: 'account:get',
    changed: 'account:changed',
  },
  history: {
    query: 'history:query',
    remove: 'history:remove',
    clear: 'history:clear',
    changed: 'history:changed',
  },
  cookies: {
    get: 'cookies:get',
    summary: 'cookies:summary',
    remove: 'cookies:remove',
    setPolicy: 'cookies:set-policy',
    setCompanyPolicy: 'cookies:set-company-policy',
    openAccountPanel: 'cookies:open-account-panel',
    changed: 'cookies:changed',
  },
  keybindings: {
    get: 'keybindings:get',
    set: 'keybindings:set',
    reset: 'keybindings:reset',
    resetAll: 'keybindings:reset-all',
    setRecording: 'keybindings:set-recording',
    changed: 'keybindings:changed',
  },
  settings: {
    get: 'settings:get',
    set: 'settings:set',
    reset: 'settings:reset',
    resetAll: 'settings:reset-all',
    restart: 'settings:restart',
    changed: 'settings:changed',
  },
  extensions: {
    get: 'extensions:get',
    prepareStore: 'extensions:prepare-store',
    prepareFolder: 'extensions:prepare-folder',
    chooseFolder: 'extensions:choose-folder',
    confirm: 'extensions:confirm',
    cancel: 'extensions:cancel',
    setEnabled: 'extensions:set-enabled',
    remove: 'extensions:remove',
    openPopup: 'extensions:open-popup',
    openOptions: 'extensions:open-options',
    clearProxy: 'extensions:clear-proxy',
    changed: 'extensions:changed',
  },
  browsers: {
    get: 'browsers:get',
    check: 'browsers:check',
    install: 'browsers:install',
    uninstall: 'browsers:uninstall',
    use: 'browsers:use',
    open: 'browsers:open',
    setStreaming: 'browsers:set-streaming',
    changed: 'browsers:changed',
  },
  themes: {
    get: 'themes:get',
    select: 'themes:select',
    add: 'themes:add',
    importFile: 'themes:import-file',
    searchVsx: 'themes:search-vsx',
    installVsx: 'themes:install-vsx',
    installPopular: 'themes:install-popular',
    remove: 'themes:remove',
    changed: 'themes:changed',
  },
  devtools: {
    get: 'devtools:get',
    use: 'devtools:use',
    check: 'devtools:check',
    download: 'devtools:download',
    uninstall: 'devtools:uninstall',
    changed: 'devtools:changed',
  },
  userCss: {
    get: 'user-css:get',
    changed: 'user-css:changed',
  },
} as const;
