import type { ThemeDefinition } from '~types/themes';

/** Chosen when the user has not picked a theme: Webswitch's own, dark or light like the desktop. */
export const SYSTEM_THEME = 'system';
export const DARK_THEME = 'webswitch-dark';
export const LIGHT_THEME = 'webswitch-light';

/** The themes that ship with Webswitch. The first two are the colors the UI always had. */
export const BUILTIN_THEMES: readonly ThemeDefinition[] = [
  {
    id: DARK_THEME,
    name: 'Webswitch Dark',
    author: 'Webswitch',
    scheme: 'dark',
    colors: {
      bg: '#000000',
      raised: '#1f1f1f',
      hover: '#272727',
      border: '#272727',
      fg: '#d3d3d3',
      fgStrong: '#eff3bc',
      fgSoft: '#bcbcbc',
      fgMuted: '#6b6b6b',
      accent: '#e8adb9',
      info: '#63afc5',
      success: '#8bc98d',
      danger: '#e8adb9',
    },
  },
  {
    id: LIGHT_THEME,
    name: 'Webswitch Light',
    author: 'Webswitch',
    scheme: 'light',
    colors: {
      bg: '#eff3bc',
      raised: '#e3e7b3',
      hover: '#d3d3d3',
      border: '#bcbcbc',
      fg: '#1a1a1a',
      fgStrong: '#000000',
      fgSoft: '#272727',
      fgMuted: '#6b6b6b',
      accent: '#e8adb9',
      info: '#409cb9',
      success: '#718f97',
      danger: '#6b6b6b',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    scheme: 'dark',
    colors: {
      bg: '#282a36',
      raised: '#343746',
      hover: '#44475a',
      border: '#44475a',
      fg: '#f8f8f2',
      fgStrong: '#ffffff',
      fgSoft: '#e0e0dc',
      fgMuted: '#6272a4',
      accent: '#bd93f9',
      info: '#8be9fd',
      success: '#50fa7b',
      danger: '#ff5555',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    scheme: 'dark',
    colors: {
      bg: '#2e3440',
      raised: '#3b4252',
      hover: '#434c5e',
      border: '#4c566a',
      fg: '#d8dee9',
      fgStrong: '#eceff4',
      fgSoft: '#e5e9f0',
      fgMuted: '#7b88a1',
      accent: '#88c0d0',
      info: '#81a1c1',
      success: '#a3be8c',
      danger: '#bf616a',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    scheme: 'dark',
    colors: {
      bg: '#282828',
      raised: '#3c3836',
      hover: '#504945',
      border: '#504945',
      fg: '#ebdbb2',
      fgStrong: '#fbf1c7',
      fgSoft: '#d5c4a1',
      fgMuted: '#928374',
      accent: '#fabd2f',
      info: '#83a598',
      success: '#b8bb26',
      danger: '#fb4934',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    scheme: 'dark',
    colors: {
      bg: '#272822',
      raised: '#3e3d32',
      hover: '#49483e',
      border: '#49483e',
      fg: '#f8f8f2',
      fgStrong: '#ffffff',
      fgSoft: '#cfcfc2',
      fgMuted: '#75715e',
      accent: '#a6e22e',
      info: '#66d9ef',
      success: '#a6e22e',
      danger: '#f92672',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    scheme: 'dark',
    colors: {
      bg: '#002b36',
      raised: '#073642',
      hover: '#0d4351',
      border: '#124a58',
      fg: '#93a1a1',
      fgStrong: '#eee8d5',
      fgSoft: '#839496',
      fgMuted: '#657b83',
      accent: '#b58900',
      info: '#268bd2',
      success: '#859900',
      danger: '#dc322f',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    scheme: 'light',
    colors: {
      bg: '#fdf6e3',
      raised: '#eee8d5',
      hover: '#e6dfc8',
      border: '#d6ceb4',
      fg: '#586e75',
      fgStrong: '#073642',
      fgSoft: '#657b83',
      fgMuted: '#93a1a1',
      accent: '#cb4b16',
      info: '#268bd2',
      success: '#859900',
      danger: '#dc322f',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    scheme: 'dark',
    colors: {
      bg: '#000000',
      raised: '#1a1a1a',
      hover: '#333333',
      border: '#ffffff',
      fg: '#ffffff',
      fgStrong: '#ffffff',
      fgSoft: '#f0f0f0',
      fgMuted: '#c0c0c0',
      accent: '#ffff00',
      info: '#00ffff',
      success: '#00ff00',
      danger: '#ff5050',
    },
  },
];
